.PHONY: all

all:
	gcc -I/usr/local/include example-3-write.c -o example-3-write.x -L/usr/local/lib -ltokyocabinet -lz -lbz2 -lrt -lpthread -lm -lc
	gcc -I/usr/local/include example-3-read.c -o example-3-read.x -L/usr/local/lib -ltokyocabinet -lz -lbz2 -lrt -lpthread -lm -lc
